fullscreen=true
winResizable=false
anyAltToggleFS=true
smoothScaling=false
vsync=false
subImageFix=true
enableBlitting=false
frameSkip=true
fixedAspectRatio=false
fixedFramerate=60

# DO NOT TOUCH
iconPath=icon.png
dataPathOrg=fummy
dataPathApp=witchhouse
preloadScript=preload/ruby18_comp.rb
preloadScript=preload/win32_wrap.rb
preloadScript=preload/translation.rb
fontSub=Arial>VL PGothic
fontSub=Times New Roman>VL PGothic
fontSub=MS Gothic>VL PGothic
fontSub=MS PGothic>VL PGothic
fontSub=MS Mincho>VL PGothic
fontSub=MS PMincho>VL PGothic
fontSub=UmePlus Gothic>VL PGothic
fontSub=Courier New>VL PGothic
fontSub=ＭＳ ゴシック>VL PGothic
fontSub=ＭＳ Ｐゴシック>VL PGothic
fontSub=ＭＳ 明朝>VL PGothic
fontSub=ＭＳ Ｐ明朝>VL PGothic
fontSub=HGP明朝E>VL PGothic
